### ISSUE TITLE
How to list more characters?

### ISSUE THREAD

**Issue by Matthew2D** [MongooseDoom/guild-roster#12]
It will only list 18 characters. My guild has 372. How do I list more?

**Comment by parkerjm** [comment]
guild members are a hard-coded list at the moment, the app would have to change substantially for something like what you want, I think

**Comment by MongooseDoom** [comment]
@Matthew2D The raid team view is a hard coded list for now and the guild view is only characters over lvl 100. 
For the raid team view, you could update $scope.guildMembers in [app.js](https://github.com/MongooseDoom/guild-roster/blob/master/app/app.js#L14).
For the guild view, you could remove level 100 if statement in $scope.getGuildList in [app.js](https://github.com/MongooseDoom/guild-roster/blob/master/app/app.js#L92).

``` javascript
    $scope.getGuildList = function(){
        $http.jsonp("http://"+$scope.regionHost+"/api/wow/guild/"+$scope.guildRealm+"/"+$scope.guildName+"?fields=members&jsonp=JSON_CALLBACK").success(function(data, status, hearders, config){
            angular.forEach(data.members, function (member, index) {
                    $scope.addCharacter(member.character.name, $scope.guildRealm);
            });
        }).error(function(data, status, hearders, config){
            $scope.errorText = "Can not load guild";
        }); // end jsonp()
    }; /* end getGuildList() */
```

I hope that helps!
